export const SUBMIT_REPORT_SUCCESS = "SUBMIT_REPORT_SUCCESS";
export const SUBMIT_REPORT_FAIL = "SUBMIT_REPORT_FAIL";
export const GET_ALL_REPORT_SUCCESS = "GET_ALL_REPORT_SUCCESS";
export const GET_ALL_REPORT_FAIL = "GET_ALL_REPORT_FAIL";
export const GET_ALL_IMAGES_SUCCESS = "GET_ALL_IMAGES_SUCCESS";
export const GET_ALL_IMAGES_FAIL = "GET_ALL_IMAGES_FAIL";
export const DOWNLOAD_IMAGES_SUCCESS = "DOWNLOAD_IMAGES_SUCCESS";
